### ISSUE TITLE
Using this code with a sim 800 module

### ISSUE THREAD

**Issue by wrenfannin** [mhhabib/Bus-tracking-using-gps-neo-6m-and-gsm-SIM900a-with-arduino#1]
Can I use the same code with a sim 800h card instead, or will I have to change anything in the code

**Comment by mhhabib** [comment]
Yes! It may be work. If you have an 800 module, please check with 800 then know me what's the result.

**Comment by wrenfannin** [comment]
I assume I just the code with the normal Arduino IDE, if yes, I'll build the circuit tomorrow

**Comment by wrenfannin** [comment]
One last question, once I build the circuit and run the code, how will I be able to track the gps module, this is my first time doing this

**Comment by wrenfannin** [comment]
> One last question, once I build the circuit and run the code, how will I be able to track the gps module, this is my first time doing this

And do you have a list of what pins I should connect to each device, (GPS to Arduino, etc...) Thanks

**Comment by mhhabib** [comment]
> ### Reply in your first question
-  You should insert a sim in **GPS** module
-  If you notice my Arduino code, you may seem I have a server and in that server, I usually accept my latest Lat, Long. Then the lat long passes to the database. Call the recent lat long to show your website. 
-  More on: Need a sim, make a server, get data from Arduino and send it to the database then show the latest Lat, Long to your website or mobile app. 

> ### Reply in your second question
[See the diagram how it designed](https://github.com/mhhabib/Bus-tracking-using-gps-neo-6m-and-gsm-SIM900a-with-arduino/blob/master/images/gsm%2Bgps%2Barduino.png)

**Comment by wrenfannin** [comment]
> > ### Reply in your first question
> -  You should insert a sim in **GPS** module
> -  If you notice my Arduino code, you may seem I have a server and in that server, I usually accept my latest Lat, Long. Then the lat long passes to the database. Call the recent lat long to show your website. 
> -  More on: Need a sim, make a server, get data from Arduino and send it to the database then show the latest Lat, Long to your website or mobile app. 
> 
> > ### Reply in your second question
> [See the diagram how it designed](https://github.com/mhhabib/Bus-tracking-using-gps-neo-6m-and-gsm-SIM900a-with-arduino/blob/master/images/gsm%2Bgps%2Barduino.png)
> 

If I don't have access to a server unless absolutely necessary, would it be possible to send the data straight to something like Google maps or an iot dashboard

**Comment by mhhabib** [comment]
Sorry no
